# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 612a752bf6922ad536c0b649c6eb39b5822a77b401358ed6618632feddb55deab91973d576e0072ba44394e55f7cb3b2fff58f83210ec0ecaf525cf9aefc6ec8

test:
  secret_key_base: 3223dc2e74d4c71bf6983460aca4644a9d41586e05a01378edac9b47c4bb76f1d71b95100980a7418525d048960ff750bf4d413a837aaf04894aa75f40c293d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
